### ISSUE TITLE
Useful error message for no hosts returned from config file

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#157]
If no hosts are returned from the config file, Aerys currently fails with `[2017-07-25 12:05:12] critical TypeError: Expected an array of Hosts as second parameter, but array also contains integer in /home/kelunik/GitHub/kelunik/chat/vendor/amphp/aerys/lib/functions.php:541`, which is not really a helpful error message.

**Comment by joshdifabio** [comment]
Have you considered that configuration would be much more developer-friendly if you used value objects (i.e. with actual classes) for configuration instead of arrays? Configuration options would be clearly documented in the code, the risk of typos in the names of optional fields would be eliminated, developers would get auto-completion in their IDEs when writing configuration, and errors/exceptions thrown as a result of misconfiguration would be thrown where the developer made the mistake, instead of later on in some distant piece of code, as has happened here.

**Comment by kelunik** [comment]
@joshdifabio I guess you're talking about `AERYS_OPTIONS`. That's not what this issue is about. It's about the new config returning `Host|Host[]` instead of relying on magic to register hosts.

**Comment by joshdifabio** [comment]
I think the issue you've raised is a symptom of the approach you guys have taken to configuration with Aerys, which is why I made the suggestion.

As far as I understand it, Aerys's `Host` objects are simply configuration, so I think something like this:
```php
function initServer(PsrLogger $logger, ServerConfiguration $configuration): Server
```

would be better than the current:
```php
function initServer(PsrLogger $logger, array $hosts, array $options = []): Server
```

For all the reasons I mentioned previously. Plus a lot of what `initServer()` does is validate the provided arguments and specify default values (e.g. debug=false), which could be moved to configuration objects.

Just a suggestion.
