### ISSUE TITLE
Run as library?

### ISSUE THREAD

**Issue by RobberPhex** [amphp/aerys#167]
When I want run a web server,
I must run `bin/aerys`.

How about run as library, like [ReactPHP](https://github.com/reactphp/http#quickstart-example).
I think there should be a http server library, artax just is http client library.

**Comment by kelunik** [comment]
Yes, you can run Aerys also as a library, see [`initServer`](https://github.com/amphp/aerys/blob/master/lib/functions.php#L530-L569). There's currently no documentation on how to do that, but it's totally doable.

**Comment by bwoebi** [comment]
Have a look at https://amphp.org/aerys/classes/functions#initpsrlogloggerinterface-arrayhost-array-options---server

This allows you controlling the `Server` instance manually and use Aerys as a library.

The main point of `bin/aerys` is ensuring that your resources on the running instance are used optimally by being your process manager. It spawns as many workers as you wish (by default: as many as there are cores), allows for proper graceful restart of all workers via CommandClient class, aggregates your logging of all your workers etc.
As long as you do not intend to use Aerys for a quick and dirty monitoring or admin interface, but for a larger audience, it is strongly recommended to use `bin/aerys` in order to be able to properly scale out in future without too much rewriting.

**Comment by RobberPhex** [comment]
we process request in callback, not in coroutine.

I think there should be a http-server lib.

socket server is good example:

https://github.com/amphp/socket/blob/e829717dad74648b34da631be1e86cbacdaa799f/examples/simple-http-server.php
```php
Loop::run(function () {
    $clientHandler = asyncCoroutine(function (ServerSocket $socket) {
        list($ip, $port) = explode(":", $socket->getRemoteAddress());
        echo "Accepted connection from {$ip}:{$port}." . PHP_EOL;
        $body = "Hey, your IP is {$ip} and your local port used is {$port}.";
        $bodyLength = \strlen($body);
        yield $socket->end("HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Length: {$bodyLength}\r\n\r\n{$body}");
    });
    $server = Amp\Socket\listen("127.0.0.1:0");
    echo "Listening for new connections on " . $server->getAddress() . " ..." . PHP_EOL;
    echo "Open your browser and visit http://" . $server->getAddress() . "/" . PHP_EOL;
    while ($socket = yield $server->accept()) {
        $clientHandler($socket);
    }
});
```

just one callback.

---

How about this demo for http? this more like coroutine(write synchronous, run asynchronous).

```php
use Amp\Loop;
use function Aerys\router;
use function Amp\asyncCoroutine;

Loop::run(function () {
    $router = router();
    $clientHandler = asyncCoroutine(function ($req, $resp) use ($router) {
        /** @var \Aerys\InternalRequest $req */
        yield $router->do($req, $resp);
    });

    $server = new \Aerys\Server('0.0.0.0', 1337);

    list($req, $resp) = yield $server->accept();
    $clientHandler($req, $resp);
});
```

**Comment by kelunik** [comment]
> we process request in callback, not in coroutine.

Every callback you pass to `Host::use` or `Router::use` _is_ a simple callback, you can just use that if you want, it doesn't have to be a coroutine.

> How about this demo for http?

Why do you want that for a rather high-level HTTP server?

**Comment by kelunik** [comment]
I'm closing due to lacking feedback. I think the important part has been answered. Feel free to respond with further feedback, we can always reopen the issue.

**Comment by kelunik** [comment]
You can find another example here:

https://github.com/kelunik/oauth-cli/blob/40f091562b9079a88ed33e042498859f7ca6415a/src/functions.php
