### ISSUE TITLE
Support listening on Unix sockets

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#168]
Currently we only support listening on IPs, but not on Unix sockets. Might be interesting if Aerys is deployed behind Nginx or another reverse proxy.

**Comment by bwoebi** [comment]
I generally like the idea.

I am wondering though how this will work with multiple binding. SO_REUSEPORT won't work here.
So only option is to force usage of socket transfer then.

Additionally, how will the signature on Host::expose() look like then? `Host::expose(string $address, int $port = 0)` and require the port being non-zero for anything not being a path (and zero for paths)?

That way it should be pretty trivial, except that we have to special case it within CommandClient::importServerSockets (in order to use so_reuseport when available on tcp sockets, but not on unix sockets - ultimately so_reuseport is the fastest way to use).

**Comment by kelunik** [comment]
Either `0` or `null` for the port, yes.

**Comment by umbri** [comment]
https://github.com/amphp/uri/issues/9

Please don't forget about this

**Comment by kelunik** [comment]
@umbri That's a separate issue.
