### ISSUE TITLE
Support Root being used for delegation

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#169]
Sometimes people don't want to add a responder directly to the `Host`, but instead delegate from an existing responder to a document root for several reasons.

Currently the default mime file is loaded on server boot within `update()`:

https://github.com/amphp/aerys/blob/f0ac1e3418bc3662bd0f91f99a2d308494bdb996/lib/Root.php#L754-L756

If `Root` is used for delegation, it isn't added to the `Host` and doesn't get any `Server` updates, thus doesn't load the file.

Another option is to use `Aerys\root`, which returns a `Bootable` instead of the `Root` instance directly for whatever reason, so it's unsuitable for that use case as well. I'd even argue that `Aerys\root` is completely useless and should be removed.

That leaves us with manually calling `Root::setOption("mimeFile", ...)`, but the mime file location isn't always the same, varying whether the calling library is at the root of composer or installed as dependency.

We should either load the default mime file when constructing `Root` or expose a constant for access.

**Comment by bwoebi** [comment]
No idea why `Root` isn't implementing `Bootable` itself. `Aerys\root()` indeed looks redundant to me and `Root` should be given a second optional arg to its constructor to allow direct setting of options.

… Just to confirm whether I have understood the issue correctly: the real problem is that the `Root` is not attached to the server (and thus doesn't load mime types either)?

The correct way is to make then your responder implement Bootable and use the returned Root instance:

```php
class MyResponder implements \Aerys\Bootable {
    private $root;
    public function boot(\Aerys\Server $server, \Psr\Log\LoggerInterface $logger): callable {
        $this->root = \Aerys\root("myDocroot", [...options...])->boot($server, $logger);
    }

    public function __invoke(\Aerys\Request $req, \Aerys\Response $res) {
        return ($this->root)($req, $res); // delegate
    }
}
```

To require proper booting, we might put an assertion into the `__invoke` function checking whether the Root instance has been properly booted first.

**Comment by kelunik** [comment]
With the current setup, this doesn't work, because the document root isn't known at server boot time, but only afterwards. I'll probably change that, but the same problem might happen in case of dynamic document roots.

**Comment by bwoebi** [comment]
I am wondering whether ServerObserver actually should notify about previous states: if you only attach when Server has already been started, then you should get a Server::STARTING and a Server::STARTED `update()` call at that place.

This would make it usable for startup at any time as well as always executing shutdown properly.

**Comment by kelunik** [comment]
We have `onStart()` now, which can be called after server start if necessary, which `update()` didn't allow.
