### ISSUE TITLE
Trailing amp in x-www-form-urlencoded post data creates empty post var

### ISSUE THREAD

**Issue by brstgt** [amphp/aerys#178]
Example:

foo=bar&

creates

[
   foo : ["bar"],
   "" : ""
]

I guess this is not an intended behaviour

**Comment by bwoebi** [comment]
Is this actually even a bug?

What do we expect in a case like `foo=bar&&baz=qux`?

**Comment by bwoebi** [comment]
I'm reopening this issue in order to discuss what the proper behavior even is. Actually, it looks to me like a trailing & introduces a new empty variable.

> The control names/values are listed in the order they appear in the document. The name is separated from the value by `=' and name/value pairs are separated from each other by `&'.
~ https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1

Technically this description requires that `=` is used in each pair. But we already do allow `foo&bar` without value.

So, there's nothing forbidding empty names nor empty values. It assumes that if there is an `&`, there is a name-value pair (or just name) on both sides of it. If there is an empty name, why shouldn't it be parsed as empty name?

`foo=bar&=baz` should be parsed as `["foo":["bar"],"":["baz"]]`
Similarly `foo=bar&=` should be parsed as `["foo":["bar"],"":[""]]`.

As mentioned, we do not require the `=` being present, so we naturally should parse `foo=bar&` as `["foo":["bar"],"":[""]]` as well.
