### ISSUE TITLE
Request attributes

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#216]
We discussed using `Middleware::class` as name for request attributes. How about using object class names instead? It works quite well for sessions, the router arguments would have to be encapsulated in an object.

At least PhpStorm could then provide automatic type hints [like that](https://github.com/amphp/aerys/blob/ae379b4ff404b2651616b462a1cc7bf06146d370/.phpstorm.meta.php). It automatically hints the name passed as argument. This could work quite well, given that only value objects should be stored there, nothing that's covered by an interface.

Additionally, I'd then throw if the attribute doesn't exist, because it's obviously a middleware misconfiguration then.

```php
// in a middleware
$user = new User(42, "kelunik");
$request->attach($user);

// in a responder
$user = $request->get(User::class);
```

**Comment by trowski** [comment]
This may be too restrictive. You're saving defining a key, but imposing the requirement that only objects may be stored and only one instance of each class name.

I do not completely dislike the idea, but I'm thinking it makes `Request` too opinionated.

Does the PhpStorm config apply to projects requiring this, or do they have to define the config themselves?

**Comment by kelunik** [comment]
As far as I know it works for all projects, at least I added it to `rdlowrey/auryn`, too.

**Comment by Ocramius** [comment]
Good idea IMO. This is becoming the defacto standard with PSR-11 consumers, and the same kind of rationale (and pitfalls) also apply here.

From a consumer perspective, rhis means having a single import and also having an idea of what type to expect, so :+1:

**Comment by trowski** [comment]
@Ocramius Good to hear you've had experience with such an API and it's worked well, as this relieves most of the reservations I had about it.

This is somewhat like dynamically adding methods to `Request`, but far less magical than `__call`.

**Comment by kelunik** [comment]
@trowski And with proper namespacing.

**Comment by assertchris** [comment]
> imposing the requirement that only objects may be stored and only one instance of each class name.

This can be side-stepped if the consumer defines a container type to house multiple instances, akin to a typed collection.

**Comment by kelunik** [comment]
Implemented via f58f633.

**Comment by kelunik** [comment]
I wonder whether there should be a `detach()` or `extract()` method or something like that.

**Comment by Ocramius** [comment]
> like that.

`#define "that"`

**Comment by kelunik** [comment]
Oops, something to remove attached attributes again.

**Comment by trowski** [comment]
Probably. `detach()` seems logical.

**Comment by bwoebi** [comment]
What would be the purpose of that removing these objects?

**Comment by kelunik** [comment]
I'm not sure, which is why I haven't implemented something like that yet.

**Comment by trowski** [comment]
`Request` is mutable and replaceable in middlewares anyway, so is their a reason to *not* allow the objects to be removed or replaced?

**Comment by joshdifabio** [comment]
I really think this design should be reconsidered, because:
- it forces us to write lots of boilerplate code (I have to create a class for every attribute I define, and these classes will generally just contain a single property)
- it is way too opinionated about type safety, essentially defining a new pattern for value bags to work around PHP's lack of generics. Even Java's ServletRequest::get/setAttribute methods don't try to validate types, as Java devs know how to do this themselves in Java. Just like PHP devs know how to do this themselves in PHP.
- it is fragile. Developers will do things like `$request->attach($datetime)` which will silently overwrite other DateTime instances which have a different meaning. Imo this is far more likely than conflicts caused by people specifying the same name for a property

I want to be able to do
```php
$request->setAttribute('request_time', $timestamp);
$request->setAttribute('current_user', $user);
$request->setAttribute('last_visit, $timestamp);
```
etc.

Essentially, the current design necessitates creating a class when all I want to do is specify the name of an attribute.

**Comment by kelunik** [comment]
@joshdifabio Suggestions are always welcome and we're open to reverting this.

 - Yes, you'd have to create a new class for each attribute, but how many attributes do you usually have?
 - It basically follows PSR-11, just adds a type declaration where PSR-11 has none. Generics wouldn't really help here.
 - I already thought about that, maybe we should just disallow all classes in the global namespace. This should avoid most conflicts.

In the example you give, I'd probably implement `$user` as a `User` object that has `getId()`, `getName()` and `getLastVisit()`, so it'd already be a class.  Your `request_time` might conflict with other such definitions, some middleware might define it as `DateTime`, some other middleware as `int` representing a unix timestamp. So this doesn't really help with the third point IMO.

So the question really boils down to which attributes will actually be present.

**Comment by joshdifabio** [comment]
> It basically follows PSR-11, just adds a type declaration where PSR-11 has none. I don't see how generics would help here.

No, this is much more prescriptive and restrictive. PSR-11 allows multiple entries of the same type, and has explicit identifiers for entries. PSR-11 is a very typical way of implementing a value bag and is actually the same way other frameworks implement request attributes.

A value bag which identifies its values solely by their type is very restrictive and I have never seen it before.

> So the question really boils down to which attributes will actually be present.

Which you can't really predict at the framework level, and you shouldn't try to do so.

> So this doesn't really help with the third point IMO.

My third point is that attributes should be explicitly identified using a string identifier, not by their type. So yes, it would help, because developers just need to ensure that the identifier is unique. My whole point is that the current design makes these conflicts far more likely because attributes are identified by their type, and some types are common. Banning the use of classes in the root namespace would just make this weirder.

**Comment by trowski** [comment]
The points made by above by @joshdifabio outline my original concerns with this API that it was too opinionated and restrictive, requiring a lot of boilerplate just to store a simple value.

@Ocramius do you have some examples where PSR-11 has been implemented like this, allowing only single instances of a class?

**Comment by Ocramius** [comment]
It is not implemented like this: it is generally just convention that the
parameter string matches the return type, but it isn't enforced. Enforcing
it wouldn't make sense, as everything would otherwise turn into a singleton.

**Comment by kelunik** [comment]
We have reverted this for now.
