### ISSUE TITLE
Max CPU cores used for worker should be one lower than the amount of system cores

### ISSUE THREAD

**Issue by dol** [amphp/aerys#66]
The WatcherProcess currently starts as many worker server as CPU cores are available on the system. This gives CPU cores + one total PHP processes. On a even distribution of the PHP processes on the CPU cores at least one worker process is fighting with the watcher process for CPU time.
This might be an issue that one worker process is hindered by the watcher workload.

**Comment by kelunik** [comment]
The worker doesn't have that much to do. Additionally this leaves one CPU core rather unused. You can always adjust it using the worker command line option.

**Comment by dol** [comment]
Ok. That was also my thought. Leaving one CPU idling around is IMHO not preferred over the small context switch of two PHP processes.

**Comment by bwoebi** [comment]
Well, to be precise, we have exactly zero context switches to master process under normal operation as kernel is in control due to kqueue()/select() syscall with no timeout for the whole time until something special (logging, worker crash, CommandClient) happens.

The only context switches are because other programs like init etc. need to run too. But it rather doesn't make much difference.

**Comment by dol** [comment]
:+1:
