### ISSUE TITLE
Add support for PROXY protocol

### ISSUE THREAD

**Issue by dol** [amphp/aerys#69]
Running a Aerys application behind a loadbalancer hides the original client IP. The [PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) was invented to pass the client informations to the backend services.
The PROXY protocol support in Aerys could be implemented as wrapper, similar to [node.js proxywrap](https://github.com/daguej/node-proxywrap).

Useful material:
http://blog.haproxy.com/haproxy/proxy-protocol/

**Comment by bwoebi** [comment]
Well, it'd require being able to define the default parsing driver to be able to hook in there.

Currently not possible, but we maybe could add an option to override the default driver on the Host instance...
Then it'd be possible to add an own raw-stream dispatcher… Currently we just have an upgrading mechanism after an initial http request.

Am I right that all you need is actually `Host::use()` accepting a custom `Aerys\HttpDriver` instance? Then you can simply write your own wrapper and go ahead with dispatching to the actual `Aerys\Http1Driver`?

**Comment by bwoebi** [comment]
Uh, I see, no, we can't do it on Host, as we don't know the actual Host ahead of time. We'll have to use a custom Driver for a whole port at least.

So, like an option mapping port to a httpDriver instance globally.

**Comment by bwoebi** [comment]
Now `Host::use()` accepts a HttpDriver instance you'll need to add on all your Hosts which are on an interface&port pair. Then instead of dispatching the raw bytes to the default drivers (Http1Driver or Http2Driver), you can do a custom parse of the raw data and adequately dispatch answers.

For implementing the proxy protocol, you need to parse the proxy protocol and you can just forward the individual requests to the Http1Driver for example. Similar for writing, you can forward the processed data to the Http1Driver, have your custom write callback and appropriately process the raw response before passing it to the write callback provided by the Server.

**Comment by bwoebi** [comment]
By the way @dol in case you need some help, you're welcome to appear in a chat (https://dev.kelunik.com/rooms/1 (Two Crowns) or https://chat.stackoverflow.com/rooms/11), I'll happily answer your questions, I just don't want to implement it myself ;-)

**Comment by dol** [comment]
@bwoebi Thank you for the rearrangement. I'll see what I can do.
