### ISSUE TITLE
Php-pm like engine via amphp

### ISSUE THREAD

**Issue by vuliad** [amphp/aerys#95]
Does someone thinking about develop "php-pm like" engine via amphp? As i experiment, it can already work nearly like php-pm and there is no a lot of work. 
What really needed to be done is - smart balancer, integrated with process manager. It has to be able to manage workers dynamicaly(increase\decrease), restart processes to prevent memory leaks(easiest way is to restart every N requests), restarting processes on code changes, debug\monitoring tools. 

I understand - that this is really not the aim of this project, but there a lot of old legacy code, that really hard to rewrite whole. And php-pm, based on reactphp, which develops too slowly, for ex. reactphp+php7 has no other event loop, except stream_select and there are many others disadvantages.

**Comment by bwoebi** [comment]
It is quite interesting to do that…one just would have to install aerys hosts (aka server config) and then dispatch to processes.

As you say, it's not aim/part of Aerys core, but you can write a separate project which is included in an Aerys config via `$host->use(new YourProject\PMDispatcher($fileRoot /* and whatever options are necessary */));` It then does the process managing as needed.

I'm not planning on doing such a project in near future, but someone of the Aerys users may feel so free. It's important to have a broad toolset in order to ever make Aerys popular ;-)

**Comment by bwoebi** [comment]
Closing as not really am Aerys problem… we need external contributors for this.

**Comment by vuliad** [comment]
Ok, i ready to start testing this.
For first step - i wanna use nginx as balancer with least_conn upstream setting. And start manually N-slave workers (managed by supervisord), that will be independently serving connections one by one. How can i implement this slave worker? I can start N-aerys instansec, but it's a bit overhead because it will be N x (1xMaster+1xSlave).

**Comment by bwoebi** [comment]
Actually, you wouldn't load balance it that way, but rather take Aerys, run it normally … and spawn workers for the requests: https://github.com/amphp/concurrent [still WIP and API going to change, but should work for now; just needs amp_v2 branch of Aerys.]

Then you can dispatch the request in these workers instead and communicate it back to the Aerys slaves.

**Comment by vuliad** [comment]
Well it looks nice. You mean Thread::spawn() and communicate via channel->send/recieve?

**Comment by bwoebi** [comment]
@vuliad You'd rather use WorkerPool (which abstracts that nicely away), but yep, basically that.
